"""empty message

Revision ID: 327c55248777
Revises: d23804992c1f
Create Date: 2023-06-08 15:44:44.072581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327c55248777'
down_revision = 'd23804992c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('birth', sa.Text(), nullable=False),
    sa.Column('death', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('profile_name', sa.String(length=200), nullable=True),
    sa.Column('profile_data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chumo_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chumo'))
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.Text(length=250), server_default='1', nullable=True))
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('relation',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('relation',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('file_data')
        batch_op.drop_column('file_name')

    op.drop_table('chumo')
    # ### end Alembic commands ###
